apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-streamlit
  template:
    metadata:
      labels:
        app: iris-streamlit
    spec:
      containers:
      - name: iris-streamlit
        image: iquantc/ml-airflow-streamlit-app:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: iris-streamlit-service
spec:
  type: NodePort
  selector:
    app: iris-streamlit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
    nodePort: 30005
  